
// This file has been generated by the GUI designer. Do not modify.
namespace II_Linux.UI
{
	public partial class DialogAbout
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget II_Linux.UI.DialogAbout
			this.Name = "II_Linux.UI.DialogAbout";
			this.Title = global::Mono.Unix.Catalog.GetString("DialogAbout");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
