using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace II.Localization {

    public class Languages {
        public Values Value;
        public Languages (Values v) { Value = v; }
        public Languages () {
            if (Enum.TryParse<Values> (CultureInfo.InstalledUICulture.ThreeLetterWindowsLanguageName.ToUpper (), out Values tryParse))
                Value = tryParse;
            else
                Value = Values.ENU;
        }

        public enum Values {
            DEU,
            ENU,
            ESP,
            FRA,
            ITA,
            PTB,
            RUS,

            /* Planned for future implementation:
            ARA,
            HEB,
            JPN,
            CHS
            */
        }

        public string Description { get { return Descriptions [(int)Value]; } }

        public static List<string> MenuItem_Formats {
            get { return Descriptions; }
        }
        public static Values Parse_MenuItem (string inc) {
            try {
                int i = Descriptions.FindIndex (o => { return o == inc; });
                if (i >= 0)
                    return (Values)Enum.GetValues (typeof (Values)).GetValue (i);
                else
                    return Values.ENU;
            } catch {
                return Values.ENU;
            }
        }

        public static List<string> Descriptions = new List<string> {
            "Deutsche (German)",
            "English",
            "Español (Spanish)",
            "Français (French)",
            "Italiano (Italian)",
            "Português (Portugese)",
            "русский (Russian)",
        };
    }


    public static class Strings {
        public static string Lookup(Languages.Values lang, string key) {
            Pair pair;
            switch (lang) {

                default:
                case Languages.Values.ENU: pair = ENU.Find (o => { return o.Index == key; }); break;

                case Languages.Values.DEU: pair = DEU.Find (o => { return o.Index == key; }); break;
                case Languages.Values.ESP: pair = ESP.Find (o => { return o.Index == key; }); break;
                case Languages.Values.FRA: pair = FRA.Find (o => { return o.Index == key; }); break;
                case Languages.Values.ITA: pair = ITA.Find (o => { return o.Index == key; }); break;
                case Languages.Values.PTB: pair = PTB.Find (o => { return o.Index == key; }); break;
                case Languages.Values.RUS: pair = RUS.Find (o => { return o.Index == key; }); break;

                /* Planned for future implementation:
                case Languages.Values.ARA: pair = ARA.Find (o => { return o.Index == key; }); break;
                case Languages.Values.HEB: pair = HEB.Find (o => { return o.Index == key; }); break;
                case Languages.Values.JPN: pair = JPN.Find (o => { return o.Index == key; }); break;
                case Languages.Values.CHS: pair = CHS.Find (o => { return o.Index == key; }); break;
                */
            }
            if (pair != null)
                return pair.Value;
            else
                return "?!ERROR?!";
        }


        public class Pair {
            public string Index { get; set; }
            public string Value { get; set; }

            public Pair () {
                Index = ""; Value = "";
            }
            public Pair (string index, string value) {
                Index = index; Value = value;
            }
        }

        static List<Pair> DEU = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Fortsetzen"),
            new Pair("BUTTON:ApplyChanges",                     "Änderungen übernehmen"),
            new Pair("BUTTON:ResetParameters",                  "Parameter zurücksetzen"),
            new Pair("II:InfirmaryIntegrated",                  "Krankenstation integriert"),
            new Pair("RHYTHM:Asystole",                         "Asystolie"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Vorhofflimmern"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Vorhofflattern"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "AV-Block, 1. Grad"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "AV-Block, 3. Grad"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "AV-Block, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "AV-Block, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Bündel Zweigblock"),
            new Pair("RHYTHM:Idioventricular",                  "Idioventrikulär"),
            new Pair("RHYTHM:Junctional",                       "Junktional"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Pulslose elektrische Aktivität"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Sinusrhythmus"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Sinusrhythmus mit Bigeminie"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Sinusrhythmus mit Trigeminie"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Sinusrhythmus mit PACs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Sinusrhythmus mit PJCs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Sinusrhythmus mit PVCs (Multifokal)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Sinusrhythmus mit PVCs (Unifokal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Supraventrikuläre Tachykardie"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Ventrikuläre Fibrillation (grob)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Kammerflimmern (fein)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Ventrikulärer Stillstand"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Ventrikuläre Tachykardie (monomorph, gepulst)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Ventrikuläre Tachykardie (monomorph, pulslos)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Ventrikuläre Tachykardie (polymorph)"),
            new Pair("RHYTHM:Apnea",                            "Apnoe"),
            new Pair("RHYTHM:Regular",                          "Regulär"),
            new Pair("PE:WindowTitle",                          "Krankenstation Integriert: Geduldig"),
            new Pair("PE:MenuFile",                             "Datei"),
            new Pair("PE:MenuLoadSimulation",                   "Lastsimulation"),
            new Pair("PE:MenuSaveSimulation",                   "Simulation speichern"),
            new Pair("PE:MenuExitProgram",                      "Ausfahrt Krankenstation Integriert"),
            new Pair("PE:MenuSettings",                         "die Einstellungen"),
            new Pair("PE:MenuSetLanguage",                      "Sprache wählen"),
            new Pair("PE:MenuHelp",                             "Hilfe"),
            new Pair("PE:MenuAboutProgram",                     "Über Krankenstation integriert"),
            new Pair("PE:Devices",                              "Geräte"),
            new Pair("PE:CardiacMonitor",                       "Herz-Monitor"),
            new Pair("PE:12LeadECG",                            "12-Kanal-EKG"),
            new Pair("PE:Defibrillator",                        "Defibrillator"),
            new Pair("PE:Ventilator",                           "Ventilator"),
            new Pair("PE:IABP",                                 "Intraaortale Ballonpumpe"),
            new Pair("PE:Cardiotocograph",                      "Kardiotokograph"),
            new Pair("PE:IVPump",                               "IV Pumpe"),
            new Pair("PE:LabResults",                           "Laborergebnisse"),
            new Pair("PE:HeartRate",                            "Puls"),
            new Pair("PE:BloodPressure",                        "Blutdruck"),
            new Pair("PE:RespiratoryRate",                      "Atemfrequenz"),
            new Pair("PE:PulseOximetry",                        "Pulsoximetrie"),
            new Pair("PE:Temperature",                          "Temperatur"),
            new Pair("PE:EndTidalCO2",                          "End Tide CO2"),
            new Pair("PE:ArterialBloodPressure",                "Arterieller Blutdruck"),
            new Pair("PE:CentralVenousPressure",                "Zentralvenöser Druck"),
            new Pair("PE:PulmonaryArteryPressure",              "Lungenarterien Druck"),
            new Pair("PE:RespiratoryRhythm",                    "Atemrhythmus"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Inspiratorisches-Exspiratorisches Verhältnis"),
            new Pair("PE:CardiacRhythm",                        "Herzrhythmus"),
            new Pair("PE:VitalSigns",                           "Vitalfunktionen"),
            new Pair("PE:AdvancedHemodynamics",                 "Fortgeschrittene Hämodynamik"),
            new Pair("PE:RespiratoryProfile",                   "Atmungsprofil"),
            new Pair("PE:CardiacProfile",                       "Herz-Profil"),
            new Pair("PE:UseDefaultVitalSignRanges",            "Verwenden Sie Standard-Vitalparameter für die Rhythmusauswahl?"),
            new Pair("PE:STSegmentElevation",                   "ST-Segmenthöhe"),
            new Pair("PE:TWaveElevation",                       "T Wellenhöhe"),
            new Pair("CM:WindowTitle",                          "Krankenstation integriert: Herzmonitor"),
            new Pair("CM:MenuDeviceOptions",                    "Geräteoptionen"),
            new Pair("CM:MenuPauseDevice",                      "Gerät anhalten"),
            new Pair("CM:MenuAddTracing",                       "füge Wellenformen hinzu"),
            new Pair("CM:MenuAddNumeric",                       "Nummer hinzufügen"),
            new Pair("CM:MenuFontSize",                         "Schriftgröße"),
            new Pair("CM:MenuFontSizeDecrease",                 "Schriftgröße verkleinern"),
            new Pair("CM:MenuFontSizeIncrease",                 "Schriftgröße vergrößern"),
            new Pair("CM:MenuColorScheme",                      "Farbschema"),
            new Pair("CM:MenuToggleFullscreen",                 "Vollbild umschalten"),
            new Pair("CM:MenuCloseDevice",                      "Gerät schließen"),
            new Pair("CM:MenuExitProgram",                      "Ausfahrt Krankenstation Integriert"),
            new Pair("CM:MenuRemoveTracing",                    "Entfernen Sie die Wellenform"),
            new Pair("CM:MenuRemoveNumeric",                    "Entfernen Sie die Nummern"),
            new Pair("CM:MenuSelectInputSource",                "Wählen Sie die Eingangsquelle"),
            new Pair("ECG:WindowTitle",                         "Krankenstation integriert: Elektrokardiograph"),
            new Pair("ECG:MenuDeviceOptions",                   "Geräteoptionen"),
            new Pair("ECG:MenuPauseDevice",                     "Gerät anhalten"),
            new Pair("ECG:MenuToggleFullscreen",                "Vollbild umschalten"),
            new Pair("ECG:MenuCloseDevice",                     "Gerät schließen"),
            new Pair("ECG:MenuExitProgram",                     "Ausfahrt Krankenstation Integriert"),
            new Pair("NUMERIC:ECG",                             "Elektrokardiograph"),
            new Pair("NUMERIC:T",                               "Temperatur"),
            new Pair("NUMERIC:RR",                              "Atemfrequenz"),
            new Pair("NUMERIC:ETCO2",                           "Endtidale Kapnographie"),
            new Pair("NUMERIC:SPO2",                            "Pulsoximetrie"),
            new Pair("NUMERIC:NIBP",                            "Nichtinvasiver Blutdruck"),
            new Pair("NUMERIC:ABP",                             "Arterieller Blutdruck"),
            new Pair("NUMERIC:CVP",                             "Zentralvenöser Druck"),
            new Pair("NUMERIC:PA",                              "Lungenarterien Druck"),
            new Pair("TRACING:ECG",                             "Elektrokardiograph"),
            new Pair("LEAD:SPO2",                               "Pulsoximetrie"),
            new Pair("LEAD:CVP",                                "Zentralvenöser Druck"),
            new Pair("LEAD:ABP",                                "Arterieller Blutdruck"),
            new Pair("LEAD:PA",                                 "Lungenarterien Druck"),
            new Pair("LEAD:RR",                                 "Atemfrequenz"),
            new Pair("LEAD:ETCO2",                              "Endtidale Kapnographie"),
            new Pair("LEAD:ECG_I",                              "Elektrokardiograph (EKG) Aussicht I"),
            new Pair("LEAD:ECG_II",                             "Elektrokardiograph (EKG) Aussicht II"),
            new Pair("LEAD:ECG_III",                            "Elektrokardiograph (EKG) Aussicht III"),
            new Pair("LEAD:ECG_AVR",                            "Elektrokardiograph (EKG) Aussicht aVR"),
            new Pair("LEAD:ECG_AVL",                            "Elektrokardiograph (EKG) Aussicht aVL"),
            new Pair("LEAD:ECG_AVF",                            "Elektrokardiograph (EKG) Aussicht aVF"),
            new Pair("LEAD:ECG_V1",                             "Elektrokardiograph (EKG) Aussicht V1"),
            new Pair("LEAD:ECG_V2",                             "Elektrokardiograph (EKG) Aussicht V2"),
            new Pair("LEAD:ECG_V3",                             "Elektrokardiograph (EKG) Aussicht V3"),
            new Pair("LEAD:ECG_V4",                             "Elektrokardiograph (EKG) Aussicht V4"),
            new Pair("LEAD:ECG_V5",                             "Elektrokardiograph (EKG) Aussicht V5"),
            new Pair("LEAD:ECG_V6",                             "Elektrokardiograph (EKG) Aussicht V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "Aussicht I"),
            new Pair("LEAD:ECG_II__SHORT",                      "Aussicht II"),
            new Pair("LEAD:ECG_III__SHORT",                     "Aussicht III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "Aussicht aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "Aussicht aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "Aussicht aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "Aussicht V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "Aussicht V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "Aussicht V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "Aussicht V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "Aussicht V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "Aussicht V6"),
            new Pair("ABOUT:AboutProgram",                      "Über Krankenstation integriert"),
            new Pair("ABOUT:Version",                           "Version {0}"),
            new Pair("ABOUT:Description",                       "Infirmary Integrated ist eine kostenlose und Open-Source-Software, die entwickelt wurde, um die medizinische Ausbildung von Medizinern, Pflegekräften und Studenten zu fördern. Infirmary Integrated wurde als umfassendes, genaues und zugängliches pädagogisches Werkzeug entwickelt und kann die Anforderungen von klinischen Simulatoren in Notfall-, Intensivpflege- und vielen anderen medizinischen und pflegerischen Bereichen erfüllen."),
            new Pair("LANG:LanguageSelection",                  "Sprachauswahl"),
            new Pair("LANG:ChooseLanguage",                     "Bitte wähle deine Sprache:"),
        };

        static List<Pair> ENU = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Continue"),
            new Pair("BUTTON:ApplyChanges",                     "Apply Changes"),
            new Pair("BUTTON:ResetParameters",                  "Reset Parameters"),
            new Pair("II:InfirmaryIntegrated",                  "Infirmary Integrated"),
            new Pair("RHYTHM:Asystole",                         "Asystole"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Atrial Fibrillation"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Atrial Flutter"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "AV Block, 1st Degree"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "AV Block, 3rd Degree"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "AV Block, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "AV Block, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Bundle Branch Block"),
            new Pair("RHYTHM:Idioventricular",                  "Idioventricular"),
            new Pair("RHYTHM:Junctional",                       "Junctional"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Pulseless Electrical Activity"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Sinus Rhythm"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Sinus Rhythm with Bigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Sinus Rhythm with Trigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Sinus Rhythm with PACs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Sinus Rhythm with PJCs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Sinus Rhythm with PVCs (Multifocal)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Sinus Rhythm with PVCs (Unifocal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Supraventricular Tachycardia"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Ventricular Fibrillation (Coarse)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Ventricular Fibrillation (Fine)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Ventricular Standstill"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Ventricular Tachycardia (Monomorphic, Pulsed)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Ventricular Tachycardia (Monomorphic, Pulseless)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Ventricular Tachycardia (Polymorphic)"),
            new Pair("RHYTHM:Apnea",                            "Apnea"),
            new Pair("RHYTHM:Regular",                          "Regular"),
            new Pair("PE:WindowTitle",                          "Infirmary Integrated: Patient Editor"),
            new Pair("PE:MenuFile",                             "_File"),
            new Pair("PE:MenuLoadSimulation",                   "_Load Simulation"),
            new Pair("PE:MenuSaveSimulation",                   "_Save Simulation"),
            new Pair("PE:MenuExitProgram",                      "E_xit Infirmary Integrated"),
            new Pair("PE:MenuSettings",                         "_Settings"),
            new Pair("PE:MenuSetLanguage",                      "Set _Language"),
            new Pair("PE:MenuHelp",                             "_Help"),
            new Pair("PE:MenuAboutProgram",                     "_About Infirmary Integrated"),
            new Pair("PE:Devices",                              "Devices"),
            new Pair("PE:CardiacMonitor",                       "Cardiac Monitor"),
            new Pair("PE:12LeadECG",                            "12 Lead ECG"),
            new Pair("PE:Defibrillator",                        "Defibrillator"),
            new Pair("PE:Ventilator",                           "Ventilator"),
            new Pair("PE:IABP",                                 "Intra-Aortic Balloon Pump"),
            new Pair("PE:Cardiotocograph",                      "Cardiotocograph"),
            new Pair("PE:IVPump",                               "IV Pump"),
            new Pair("PE:LabResults",                           "Laboratory Results"),
            new Pair("PE:HeartRate",                            "Heart Rate"),
            new Pair("PE:BloodPressure",                        "Blood Pressure"),
            new Pair("PE:RespiratoryRate",                      "Respiratory Rate"),
            new Pair("PE:PulseOximetry",                        "Pulse Oximetry"),
            new Pair("PE:Temperature",                          "Temperature"),
            new Pair("PE:EndTidalCO2",                          "End Tidal CO2"),
            new Pair("PE:ArterialBloodPressure",                "Arterial Blood Pressure"),
            new Pair("PE:CentralVenousPressure",                "Central Venous Pressure"),
            new Pair("PE:PulmonaryArteryPressure",              "Pulmonary Artery Pressure"),
            new Pair("PE:RespiratoryRhythm",                    "Respiratory Rhythm"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Inspiratory-Expiratory Ratio"),
            new Pair("PE:CardiacRhythm",                        "Cardiac Rhythm"),
            new Pair("PE:VitalSigns",                           "Vital Signs"),
            new Pair("PE:AdvancedHemodynamics",                 "Advanced Hemodynamics"),
            new Pair("PE:RespiratoryProfile",                   "Respiratory Profile"),
            new Pair("PE:CardiacProfile",                       "Cardiac Profile"),
            new Pair("PE:UseDefaultVitalSignRanges",            "Use default vital sign ranges for rhythm selections?"),
            new Pair("PE:STSegmentElevation",                   "ST Segment Elevation"),
            new Pair("PE:TWaveElevation",                       "T Wave Elevation"),
            new Pair("CM:WindowTitle",                          "Infirmary Integrated: Cardiac Monitor"),
            new Pair("CM:MenuDeviceOptions",                    "_Device Options"),
            new Pair("CM:MenuPauseDevice",                      "_Pause Device"),
            new Pair("CM:MenuAddTracing",                       "Add _Tracing"),
            new Pair("CM:MenuAddNumeric",                       "Add _Numeric"),
            new Pair("CM:MenuFontSize",                         "F_ont Size"),
            new Pair("CM:MenuFontSizeDecrease",                 "_Decrease Size"),
            new Pair("CM:MenuFontSizeIncrease",                 "_Increase Size"),
            new Pair("CM:MenuColorScheme",                      "Color _Scheme"),
            new Pair("CM:MenuToggleFullscreen",                 "Toggle _Fullscreen"),
            new Pair("CM:MenuCloseDevice",                      "_Close Device"),
            new Pair("CM:MenuExitProgram",                      "E_xit Infirmary Integrated"),
            new Pair("CM:MenuRemoveTracing",                    "Remove Tracing"),
            new Pair("CM:MenuRemoveNumeric",                    "Remove Numeric"),
            new Pair("CM:MenuSelectInputSource",                "Select Input:"),
            new Pair("ECG:WindowTitle",                         "Infirmary Integrated: Electrocardiogram"),
            new Pair("ECG:MenuDeviceOptions",                   "_Device Options"),
            new Pair("ECG:MenuPauseDevice",                     "_Pause Device"),
            new Pair("ECG:MenuToggleFullscreen",                "Toggle _Fullscreen"),
            new Pair("ECG:MenuCloseDevice",                     "_Close Device"),
            new Pair("ECG:MenuExitProgram",                     "E_xit Infirmary Integrated"),
            new Pair("NUMERIC:ECG",                             "Electrocardiograph"),
            new Pair("NUMERIC:T",                               "Temperature"),
            new Pair("NUMERIC:RR",                              "Respiratory Rate"),
            new Pair("NUMERIC:ETCO2",                           "End-tidal Capnography"),
            new Pair("NUMERIC:SPO2",                            "Pulse Oximetry"),
            new Pair("NUMERIC:NIBP",                            "Non-invasive Blood Pressure"),
            new Pair("NUMERIC:ABP",                             "Arterial Blood Pressure"),
            new Pair("NUMERIC:CVP",                             "Central Venous Pressure"),
            new Pair("NUMERIC:PA",                              "Pulmonary Artery Pressure"),
            new Pair("TRACING:ECG",                             "Electrocardiograph"),
            new Pair("LEAD:SPO2",                               "Pulse Oximetry"),
            new Pair("LEAD:CVP",                                "Central Venous Pressure"),
            new Pair("LEAD:ABP",                                "Arterial Blood Pressure"),
            new Pair("LEAD:PA",                                 "Pulmonary Artery Pressure"),
            new Pair("LEAD:RR",                                 "Respiratory Rate"),
            new Pair("LEAD:ETCO2",                              "End-tidal Capnography"),
            new Pair("LEAD:ECG_I",                              "Electrocardiograph (ECG) Lead I"),
            new Pair("LEAD:ECG_II",                             "Electrocardiograph (ECG) Lead II"),
            new Pair("LEAD:ECG_III",                            "Electrocardiograph (ECG) Lead III"),
            new Pair("LEAD:ECG_AVR",                            "Electrocardiograph (ECG) Lead aVR"),
            new Pair("LEAD:ECG_AVL",                            "Electrocardiograph (ECG) Lead aVL"),
            new Pair("LEAD:ECG_AVF",                            "Electrocardiograph (ECG) Lead aVF"),
            new Pair("LEAD:ECG_V1",                             "Electrocardiograph (ECG) Lead V1"),
            new Pair("LEAD:ECG_V2",                             "Electrocardiograph (ECG) Lead V2"),
            new Pair("LEAD:ECG_V3",                             "Electrocardiograph (ECG) Lead V3"),
            new Pair("LEAD:ECG_V4",                             "Electrocardiograph (ECG) Lead V4"),
            new Pair("LEAD:ECG_V5",                             "Electrocardiograph (ECG) Lead V5"),
            new Pair("LEAD:ECG_V6",                             "Electrocardiograph (ECG) Lead V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "Lead I"),
            new Pair("LEAD:ECG_II__SHORT",                      "Lead II"),
            new Pair("LEAD:ECG_III__SHORT",                     "Lead III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "Lead aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "Lead aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "Lead aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "Lead V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "Lead V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "Lead V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "Lead V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "Lead V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "Lead V6"),
            new Pair("ABOUT:AboutProgram",                      "About Infirmary Integrated"),
            new Pair("ABOUT:Version",                           "Version {0}"),
            new Pair("ABOUT:Description",                       "Infirmary Integrated is free and open-source software developed to advance healthcare education for medical and nursing professionals and students. Developed as in-depth, accurate, and accessible educational tools, Infirmary Integrated can meet the needs of clinical simulators in emergency, critical care, and many other medical and nursing specialties."),
            new Pair("LANG:LanguageSelection",                  "Language Selection"),
            new Pair("LANG:ChooseLanguage",                     "Please choose your language:"),
        };

        static List<Pair> ESP = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Continuar"),
            new Pair("BUTTON:ApplyChanges",                     "Aplicar cambios"),
            new Pair("BUTTON:ResetParameters",                  "Restablecer parámetros"),
            new Pair("II:InfirmaryIntegrated",                  "Enfermería integrada"),
            new Pair("RHYTHM:Asystole",                         "Asistolia"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Fibrilación auricular"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Aleteo auricular"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "Bloque AV, 1er grado"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "Bloque AV, 3er Grado"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "Bloque AV, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "AV Block, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Bundle Branch Block"),
            new Pair("RHYTHM:Idioventricular",                  "Idioventricular"),
            new Pair("RHYTHM:Junctional",                       "Junctional"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Actividad eléctrica sin pulso"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Ritmo sinusal"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Ritmo sinusal con Bigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Ritmo sinusal con Trigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Ritmo sinusal con PAC"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Ritmo sinusal con PJCs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Ritmo sinusal con PVC (multifocal)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Ritmo sinusal con PVC (Unifocal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Taquicardia supraventricular"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Fibrilación ventricular (gruesa)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Fibrilación ventricular (Fina)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Ventricular parado"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Taquicardia ventricular (monomórfica, pulsada)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Taquicardia ventricular (monomórfica, sin pulso)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Taquicardia ventricular (polimórfica)"),
            new Pair("RHYTHM:Apnea",                            "Apnea"),
            new Pair("RHYTHM:Regular",                          "Regular"),
            new Pair("PE:WindowTitle",                          "Enfermería Integrada: Paciente Editor"),
            new Pair("PE:MenuFile",                             "Archivo"),
            new Pair("PE:MenuLoadSimulation",                   "Simulación de carga"),
            new Pair("PE:MenuSaveSimulation",                   "Guardar Simulación"),
            new Pair("PE:MenuExitProgram",                      "Salida Enfermería Integrada"),
            new Pair("PE:MenuSettings",                         "Configuraciones"),
            new Pair("PE:MenuSetLanguage",                      "Elegir lenguaje"),
            new Pair("PE:MenuHelp",                             "Ayuda"),
            new Pair("PE:MenuAboutProgram",                     "Acerca de Infirmary Integrated"),
            new Pair("PE:Devices",                              "Dispositivos"),
            new Pair("PE:CardiacMonitor",                       "Monitor cardíaco"),
            new Pair("PE:12LeadECG",                            "12 ECG de plomo"),
            new Pair("PE:Defibrillator",                        "Desfibrilador"),
            new Pair("PE:Ventilator",                           "Ventilador"),
            new Pair("PE:IABP",                                 "Bomba de globo intraaórtica"),
            new Pair("PE:Cardiotocograph",                      "Cardiotocograph"),
            new Pair("PE:IVPump",                               "Bomba IV"),
            new Pair("PE:LabResults",                           "Resultados de laboratorio"),
            new Pair("PE:HeartRate",                            "Ritmo cardiaco"),
            new Pair("PE:BloodPressure",                        "Presión sanguínea"),
            new Pair("PE:RespiratoryRate",                      "La frecuencia respiratoria"),
            new Pair("PE:PulseOximetry",                        "Oximetría de pulso"),
            new Pair("PE:Temperature",                          "Temperatura"),
            new Pair("PE:EndTidalCO2",                          "Capnografía mareal final"),
            new Pair("PE:ArterialBloodPressure",                "Presión Arterial"),
            new Pair("PE:CentralVenousPressure",                "Presión venosa central"),
            new Pair("PE:PulmonaryArteryPressure",              "Presión arterial pulmonar"),
            new Pair("PE:RespiratoryRhythm",                    "Ritmo respiratorio"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Relación inspiratoria-espiratoria"),
            new Pair("PE:CardiacRhythm",                        "Ritmo cardiaco"),
            new Pair("PE:VitalSigns",                           "Signos vitales"),
            new Pair("PE:AdvancedHemodynamics",                 "Hemodinámica avanzada"),
            new Pair("PE:RespiratoryProfile",                   "Perfil respiratorio"),
            new Pair("PE:CardiacProfile",                       "Perfil cardiaco"),
            new Pair("PE:UseDefaultVitalSignRanges",            "¿Utiliza los rangos de signos vitales por defecto para las selecciones de ritmo?"),
            new Pair("PE:STSegmentElevation",                   "Elevación del segmento ST"),
            new Pair("PE:TWaveElevation",                       "Elevación de onda T"),
            new Pair("CM:WindowTitle",                          "Enfermería integrada: monitor cardíaco"),
            new Pair("CM:MenuDeviceOptions",                    "Opciones del aparato"),
            new Pair("CM:MenuPauseDevice",                      "Pausa el dispositivo"),
            new Pair("CM:MenuAddTracing",                       "agregar formas de onda"),
            new Pair("CM:MenuAddNumeric",                       "Añade un número"),
            new Pair("CM:MenuFontSize",                         "Tamaño de fuente"),
            new Pair("CM:MenuFontSizeDecrease",                 "Disminuir tamaño de letra"),
            new Pair("CM:MenuFontSizeIncrease",                 "Aumenta el tamaño de la fuente"),
            new Pair("CM:MenuColorScheme",                      "Esquema de colores"),
            new Pair("CM:MenuToggleFullscreen",                 "Alternar pantalla completa"),
            new Pair("CM:MenuCloseDevice",                      "Cerrar dispositivo"),
            new Pair("CM:MenuExitProgram",                      "Salida Enfermería Integrada"),
            new Pair("CM:MenuRemoveTracing",                    "Eliminar forma de onda"),
            new Pair("CM:MenuRemoveNumeric",                    "Eliminar números"),
            new Pair("CM:MenuSelectInputSource",                "Seleccionar fuente de entrada"),
            new Pair("ECG:WindowTitle",                         "Enfermería integrada: Electrocardiografía"),
            new Pair("ECG:MenuDeviceOptions",                   "Opciones del aparato"),
            new Pair("ECG:MenuPauseDevice",                     "Pausa el dispositivo"),
            new Pair("ECG:MenuToggleFullscreen",                "Alternar pantalla completa"),
            new Pair("ECG:MenuCloseDevice",                     "Cerrar dispositivo"),
            new Pair("ECG:MenuExitProgram",                     "Salida Enfermería Integrada"),
            new Pair("NUMERIC:ECG",                             "Electrocardiografía"),
            new Pair("NUMERIC:T",                               "Temperatura"),
            new Pair("NUMERIC:RR",                              "La frecuencia respiratoria"),
            new Pair("NUMERIC:ETCO2",                           "Capnografía de marea final"),
            new Pair("NUMERIC:SPO2",                            "Oximetría de pulso"),
            new Pair("NUMERIC:NIBP",                            "Presión arterial no invasiva"),
            new Pair("NUMERIC:ABP",                             "Presión Arterial"),
            new Pair("NUMERIC:CVP",                             "Presión venosa central"),
            new Pair("NUMERIC:PA",                              "Presión arterial pulmonar"),
            new Pair("TRACING:ECG",                             "Electrocardiografía"),
            new Pair("LEAD:SPO2",                               "Oximetría de pulso"),
            new Pair("LEAD:CVP",                                "Presión venosa central"),
            new Pair("LEAD:ABP",                                "Presión Arterial"),
            new Pair("LEAD:PA",                                 "Presión arterial pulmonar"),
            new Pair("LEAD:RR",                                 "La frecuencia respiratoria"),
            new Pair("LEAD:ETCO2",                              "Capnografía del final de la marea"),
            new Pair("LEAD:ECG_I",                              "Electrocardiógrafo (ECG) Vista I"),
            new Pair("LEAD:ECG_II",                             "Electrocardiógrafo (ECG) Vista II"),
            new Pair("LEAD:ECG_III",                            "Electrocardiógrafo (ECG) Vista III"),
            new Pair("LEAD:ECG_AVR",                            "Electrocardiograph (ECG) Vista aVR"),
            new Pair("LEAD:ECG_AVL",                            "Electrocardiógrafo (ECG) Vista aVL"),
            new Pair("LEAD:ECG_AVF",                            "Electrocardiógrafo (ECG) Vista aVF"),
            new Pair("LEAD:ECG_V1",                             "Electrocardiógrafo (ECG) Vista V1"),
            new Pair("LEAD:ECG_V2",                             "Electrocardiógrafo (ECG) Vista V2"),
            new Pair("LEAD:ECG_V3",                             "Electrocardiógrafo (ECG) Vista V3"),
            new Pair("LEAD:ECG_V4",                             "Electrocardiógrafo (ECG) Vista V4"),
            new Pair("LEAD:ECG_V5",                             "Electrocardiógrafo (ECG) Vista V5"),
            new Pair("LEAD:ECG_V6",                             "Electrocardiógrafo (ECG) Vista V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "Vista I"),
            new Pair("LEAD:ECG_II__SHORT",                      "Vista II"),
            new Pair("LEAD:ECG_III__SHORT",                     "Vista III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "Vista aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "Vista aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "Vista aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "Vista V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "Vista V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "Vista V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "Vista V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "Vista V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "Vista V6"),
            new Pair("ABOUT:AboutProgram",                      "Acerca de Infirmary Integrated"),
            new Pair("ABOUT:Version",                           "Versión {0}"),
            new Pair("ABOUT:Description",                       "Infirmary Integrated es un software gratuito y de código abierto desarrollado para promover la educación sanitaria para profesionales y estudiantes de medicina y enfermería. Desarrollado como herramientas educativas profundas, precisas y accesibles, Infirmary Integrated puede satisfacer las necesidades de los simuladores clínicos en emergencias, cuidados intensivos y muchas otras especialidades médicas y de enfermería."),
            new Pair("LANG:LanguageSelection",                  "Selección de idioma"),
            new Pair("LANG:ChooseLanguage",                     "Por favor elija su idioma:"),
        };

        static List<Pair> FRA = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Continuer"),
            new Pair("BUTTON:ApplyChanges",                     "Appliquer les modifications"),
            new Pair("BUTTON:ResetParameters",                  "Réinitialiser les paramètres"),
            new Pair("II:InfirmaryIntegrated",                  "Infirmerie intégrée"),
            new Pair("RHYTHM:Asystole",                         "Asystole"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Fibrillation auriculaire"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Flutter atrial"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "Bloc AV, 1er degré"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "Bloc AV, 3e degré"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "Bloc AV, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "Bloc AV, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Bundle Branch Block"),
            new Pair("RHYTHM:Idioventricular",                  "Idioventriculaire"),
            new Pair("RHYTHM:Junctional",                       "Jonctionnel"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Activité électrique sans pouls"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Un rythme sinusal"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Rythme sinusal avec Bigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Rythme sinusal avec Trigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Rythme sinusal avec PACs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Rythme sinusal avec PJC"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Rythme sinusal avec PVC (multifocal)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Rythme sinusal avec PVC (Unifocal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Tachycardie supraventriculaire"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Fibrillation ventriculaire (grossière)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Fibrillation ventriculaire (Fine)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Arrêt ventriculaire"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Tachycardie ventriculaire (monomorphique, pulsée)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Tachycardie ventriculaire (monomorphic, pulseless)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Tachycardie ventriculaire (polymorphe)"),
            new Pair("RHYTHM:Apnea",                            "Apnée"),
            new Pair("RHYTHM:Regular",                          "Ordinaire"),
            new Pair("PE:WindowTitle",                          "Infirmerie Intégrée: Patient Éditeur"),
            new Pair("PE:MenuFile",                             "Fichier"),
            new Pair("PE:MenuLoadSimulation",                   "Simulation de chargement"),
            new Pair("PE:MenuSaveSimulation",                   "Enregistrer la simulation"),
            new Pair("PE:MenuExitProgram",                      "Sortie Infirmerie Intégrée"),
            new Pair("PE:MenuSettings",                         "Paramètres"),
            new Pair("PE:MenuSetLanguage",                      "Définir la langue"),
            new Pair("PE:MenuHelp",                             "Aidez-moi"),
            new Pair("PE:MenuAboutProgram",                     "À propos d'Infirmary Integrated"),
            new Pair("PE:Devices",                              "Dispositifs"),
            new Pair("PE:CardiacMonitor",                       "Moniteur cardiaque"),
            new Pair("PE:12LeadECG",                            "12 dérivations ECG"),
            new Pair("PE:Defibrillator",                        "Défibrillateur"),
            new Pair("PE:Ventilator",                           "Ventilateur"),
            new Pair("PE:IABP",                                 "Pompe à ballon intra-aortique"),
            new Pair("PE:Cardiotocograph",                      "Cardiotocographe"),
            new Pair("PE:IVPump",                               "Pompe IV"),
            new Pair("PE:LabResults",                           "Résultats de laboratoire"),
            new Pair("PE:HeartRate",                            "Rythme cardiaque"),
            new Pair("PE:BloodPressure",                        "Tension artérielle"),
            new Pair("PE:RespiratoryRate",                      "Fréquence respiratoire"),
            new Pair("PE:PulseOximetry",                        "Oxymétrie de pouls"),
            new Pair("PE:Temperature",                          "Température"),
            new Pair("PE:EndTidalCO2",                          "Fin du CO2 marémotrice"),
            new Pair("PE:ArterialBloodPressure",                "Pression artérielle artérielle"),
            new Pair("PE:CentralVenousPressure",                "Pression veineuse centrale"),
            new Pair("PE:PulmonaryArteryPressure",              "Pression artérielle pulmonaire"),
            new Pair("PE:RespiratoryRhythm",                    "Rythme respiratoire"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Ratio inspiratoire-expiratoire"),
            new Pair("PE:CardiacRhythm",                        "Rythme cardiaque"),
            new Pair("PE:VitalSigns",                           "Signes vitaux"),
            new Pair("PE:AdvancedHemodynamics",                 "Hémodynamique avancée"),
            new Pair("PE:RespiratoryProfile",                   "Profil respiratoire"),
            new Pair("PE:CardiacProfile",                       "Profil cardiaque"),
            new Pair("PE:UseDefaultVitalSignRanges",            "Utiliser les plages de signes vitaux par défaut pour les sélections de rythme?"),
            new Pair("PE:STSegmentElevation",                   "Élévation du segment ST"),
            new Pair("PE:TWaveElevation",                       "T élévation d'onde"),
            new Pair("CM:WindowTitle",                          "Infirmerie intégrée: moniteur cardiaque"),
            new Pair("CM:MenuDeviceOptions",                    "Options de l'appareil"),
            new Pair("CM:MenuPauseDevice",                      "Mettre le périphérique en veille"),
            new Pair("CM:MenuAddTracing",                       "ajouter des formes d'onde"),
            new Pair("CM:MenuAddNumeric",                       "ajouter un numéro"),
            new Pair("CM:MenuFontSize",                         "Taille de police"),
            new Pair("CM:MenuFontSizeDecrease",                 "Diminuer la taille de la police"),
            new Pair("CM:MenuFontSizeIncrease",                 "Augmenter la taille des caractères"),
            new Pair("CM:MenuColorScheme",                      "Schéma de couleur"),
            new Pair("CM:MenuToggleFullscreen",                 "Basculer en plein écran"),
            new Pair("CM:MenuCloseDevice",                      "Fermer le périphérique"),
            new Pair("CM:MenuExitProgram",                      "Sortie Infirmerie Intégrée"),
            new Pair("CM:MenuRemoveTracing",                    "Supprimer la forme d'onde"),
            new Pair("CM:MenuRemoveNumeric",                    "Supprimer les numéros"),
            new Pair("CM:MenuSelectInputSource",                "Sélectionnez la source d'entrée"),
            new Pair("ECG:WindowTitle",                         "Infirmerie intégrée: Électrocardiographe"),
            new Pair("ECG:MenuDeviceOptions",                   "Options de l'appareil"),
            new Pair("ECG:MenuPauseDevice",                     "Mettre le périphérique en veille"),
            new Pair("ECG:MenuToggleFullscreen",                "Basculer en plein écran"),
            new Pair("ECG:MenuCloseDevice",                     "Fermer le périphérique"),
            new Pair("ECG:MenuExitProgram",                     "Sortie Infirmerie Intégrée"),
            new Pair("NUMERIC:ECG",                             "Électrocardiographe"),
            new Pair("NUMERIC:T",                               "Température"),
            new Pair("NUMERIC:RR",                              "Fréquence respiratoire"),
            new Pair("NUMERIC:ETCO2",                           "Fin Capnographie marémotrice"),
            new Pair("NUMERIC:SPO2",                            "Oxymétrie de pouls"),
            new Pair("NUMERIC:NIBP",                            "Pression artérielle non invasive"),
            new Pair("NUMERIC:ABP",                             "Pression artérielle artérielle"),
            new Pair("NUMERIC:CVP",                             "Pression veineuse centrale"),
            new Pair("NUMERIC:PA",                              "Pression artérielle pulmonaire"),
            new Pair("TRACING:ECG",                             "Électrocardiographe"),
            new Pair("LEAD:SPO2",                               "Oxymétrie de pouls"),
            new Pair("LEAD:CVP",                                "Pression veineuse centrale"),
            new Pair("LEAD:ABP",                                "Pression artérielle artérielle"),
            new Pair("LEAD:PA",                                 "Pression artérielle pulmonaire"),
            new Pair("LEAD:RR",                                 "Fréquence respiratoire"),
            new Pair("LEAD:ETCO2",                              "Fin Capnographie marémotrice"),
            new Pair("LEAD:ECG_I",                              "Électrocardiographe Voir I"),
            new Pair("LEAD:ECG_II",                             "Électrocardiographe Voir II"),
            new Pair("LEAD:ECG_III",                            "Électrocardiographe Voir III"),
            new Pair("LEAD:ECG_AVR",                            "Électrocardiographe Voir aVR"),
            new Pair("LEAD:ECG_AVL",                            "Électrocardiographe Voir aVL"),
            new Pair("LEAD:ECG_AVF",                            "Électrocardiographe Voir aVF"),
            new Pair("LEAD:ECG_V1",                             "Électrocardiographe Voir V1"),
            new Pair("LEAD:ECG_V2",                             "Électrocardiographe Voir V2"),
            new Pair("LEAD:ECG_V3",                             "Électrocardiographe Voir V3"),
            new Pair("LEAD:ECG_V4",                             "Électrocardiographe Voir V4"),
            new Pair("LEAD:ECG_V5",                             "Électrocardiographe Voir V5"),
            new Pair("LEAD:ECG_V6",                             "Électrocardiographe Voir V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "Voir I"),
            new Pair("LEAD:ECG_II__SHORT",                      "Voir II"),
            new Pair("LEAD:ECG_III__SHORT",                     "Voir III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "Voir aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "Voir aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "Voir aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "Voir V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "Voir V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "Voir V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "Voir V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "Voir V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "Voir V6"),
            new Pair("ABOUT:AboutProgram",                      "À propos d'Infirmary Integrated"),
            new Pair("ABOUT:Version",                           "Version {0}"),
            new Pair("ABOUT:Description",                       "Infirmary Integrated est un logiciel gratuit et open-source développé pour faire progresser l'éducation sanitaire pour les professionnels médicaux et infirmiers et les étudiants. Développé comme des outils éducatifs approfondis, précis et accessibles, Infirmary Integrated peut répondre aux besoins des simulateurs cliniques en urgence, en soins intensifs et dans de nombreuses autres spécialités médicales et infirmières."),
            new Pair("LANG:LanguageSelection",                  "Sélection de la langue"),
            new Pair("LANG:ChooseLanguage",                     "S'il vous plaît Choisissez votre langue:"),
        };

        static List<Pair> ITA = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Continua"),
            new Pair("BUTTON:ApplyChanges",                     "Applica i cambiamenti"),
            new Pair("BUTTON:ResetParameters",                  "Ripristina i parametri"),
            new Pair("II:InfirmaryIntegrated",                  "Infermeria integrata"),
            new Pair("RHYTHM:Asystole",                         "asistolia"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Fibrillazione atriale"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Flutter atriale"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "Blocco AV, 1o grado"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "Blocco AV, 3 ° grado"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "Blocco AV, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "Blocco AV, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Bundle Branch Block"),
            new Pair("RHYTHM:Idioventricular",                  "idioventricolare"),
            new Pair("RHYTHM:Junctional",                       "giunzionale"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Attività elettrica senza pulsazioni"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Ritmo sinusale"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Ritmo sinusale con Bigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Ritmo sinusale con Trigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Ritmo sinusale con PAC"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Ritmo sinusale con PJC"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Ritmo sinusale con PVC (Multifocale)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Ritmo sinusale con PVC (Unifocal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Tachicardia sopraventricolare"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Fibrillazione ventricolare (grossolana)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Fibrillazione ventricolare (fine)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Ventricular Standstill"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Tachicardia ventricolare (monomorfica, pulsata)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Tachicardia ventricolare (monomorfica, senza polso)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Tachicardia ventricolare (polimorfica)"),
            new Pair("RHYTHM:Apnea",                            "Apnea"),
            new Pair("RHYTHM:Regular",                          "Regolare"),
            new Pair("PE:WindowTitle",                          "Infermeria Integrata: Editor Paziente"),
            new Pair("PE:MenuFile",                             "File"),
            new Pair("PE:MenuLoadSimulation",                   "Carica simulazione"),
            new Pair("PE:MenuSaveSimulation",                   "Salva simulazione"),
            new Pair("PE:MenuExitProgram",                      "Esci dall'Infermeria Integrata"),
            new Pair("PE:MenuSettings",                         "Impostazioni"),
            new Pair("PE:MenuSetLanguage",                      "Imposta lingua"),
            new Pair("PE:MenuHelp",                             "Aiuto"),
            new Pair("PE:MenuAboutProgram",                     "Informazioni sull'infermeria integrata"),
            new Pair("PE:Devices",                              "dispositivi"),
            new Pair("PE:CardiacMonitor",                       "Monitor cardiaco"),
            new Pair("PE:12LeadECG",                            "12 elettrocatetere"),
            new Pair("PE:Defibrillator",                        "Defibrillatore"),
            new Pair("PE:Ventilator",                           "Ventilatore"),
            new Pair("PE:IABP",                                 "Pompa a palloncino intra-aortica"),
            new Pair("PE:Cardiotocograph",                      "Cardiotocografo"),
            new Pair("PE:IVPump",                               "Pompa IV"),
            new Pair("PE:LabResults",                           "Risultati di laboratorio"),
            new Pair("PE:HeartRate",                            "Frequenza cardiaca"),
            new Pair("PE:BloodPressure",                        "Pressione sanguigna"),
            new Pair("PE:RespiratoryRate",                      "Frequenza respiratoria"),
            new Pair("PE:PulseOximetry",                        "Pulsossimetria"),
            new Pair("PE:Temperature",                          "Temperatura"),
            new Pair("PE:EndTidalCO2",                          "End Tidal CO2"),
            new Pair("PE:ArterialBloodPressure",                "Pressione arteriosa"),
            new Pair("PE:CentralVenousPressure",                "Pressione venosa centrale"),
            new Pair("PE:PulmonaryArteryPressure",              "Pressione arteriosa polmonare"),
            new Pair("PE:RespiratoryRhythm",                    "Ritmo respiratorio"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Rapporto inspiratorio-espiratorio"),
            new Pair("PE:CardiacRhythm",                        "Ritmo cardiaco"),
            new Pair("PE:VitalSigns",                           "Segni vitali"),
            new Pair("PE:AdvancedHemodynamics",                 "Emodinamica avanzata"),
            new Pair("PE:RespiratoryProfile",                   "Profilo respiratorio"),
            new Pair("PE:CardiacProfile",                       "Profilo cardiaco"),
            new Pair("PE:UseDefaultVitalSignRanges",            "Utilizzare gli intervalli di segni vitali predefiniti per le selezioni del ritmo?"),
            new Pair("PE:STSegmentElevation",                   "Elevazione del segmento ST"),
            new Pair("PE:TWaveElevation",                       "T Wave Elevation"),
            new Pair("CM:WindowTitle",                          "Infermeria integrata: monitor cardiaco"),
            new Pair("CM:MenuDeviceOptions",                    "Opzioni del dispositivo"),
            new Pair("CM:MenuPauseDevice",                      "Metti in pausa il dispositivo"),
            new Pair("CM:MenuAddTracing",                       "Aggiungi forme d'onda"),
            new Pair("CM:MenuAddNumeric",                       "Aggiungi numero"),
            new Pair("CM:MenuFontSize",                         "Dimensione del font"),
            new Pair("CM:MenuFontSizeDecrease",                 "Diminuisci la dimensione del carattere"),
            new Pair("CM:MenuFontSizeIncrease",                 "Aumenta la dimensione del carattere"),
            new Pair("CM:MenuColorScheme",                      "Combinazione di colori"),
            new Pair("CM:MenuToggleFullscreen",                 "Passare a schermo intero"),
            new Pair("CM:MenuCloseDevice",                      "Chiudi dispositivo"),
            new Pair("CM:MenuExitProgram",                      "Esci dall'Infermeria Integrata"),
            new Pair("CM:MenuRemoveTracing",                    "Rimuovi la forma d'onda"),
            new Pair("CM:MenuRemoveNumeric",                    "Rimuovi numeri"),
            new Pair("CM:MenuSelectInputSource",                "Seleziona la sorgente di input"),
            new Pair("ECG:WindowTitle",                         "Infermeria integrata: Elettrocardiografo"),
            new Pair("ECG:MenuDeviceOptions",                   "Opzioni del dispositivo"),
            new Pair("ECG:MenuPauseDevice",                     "Metti in pausa il dispositivo"),
            new Pair("ECG:MenuToggleFullscreen",                "Passare a schermo intero"),
            new Pair("ECG:MenuCloseDevice",                     "Chiudi dispositivo"),
            new Pair("ECG:MenuExitProgram",                     "Esci dall'Infermeria Integrata"),
            new Pair("NUMERIC:ECG",                             "Elettrocardiografo"),
            new Pair("NUMERIC:T",                               "Temperatura"),
            new Pair("NUMERIC:RR",                              "Frequenza respiratoria"),
            new Pair("NUMERIC:ETCO2",                           "Fine capnografia di marea"),
            new Pair("NUMERIC:SPO2",                            "Pulsossimetria"),
            new Pair("NUMERIC:NIBP",                            "Pressione sanguigna non invasiva"),
            new Pair("NUMERIC:ABP",                             "Pressione arteriosa"),
            new Pair("NUMERIC:CVP",                             "Pressione venosa centrale"),
            new Pair("NUMERIC:PA",                              "Pressione arteriosa polmonare"),
            new Pair("TRACING:ECG",                             "Elettrocardiografo"),
            new Pair("LEAD:SPO2",                               "Pulsossimetria"),
            new Pair("LEAD:CVP",                                "Pressione venosa centrale"),
            new Pair("LEAD:ABP",                                "Pressione arteriosa"),
            new Pair("LEAD:PA",                                 "Pressione arteriosa polmonare"),
            new Pair("LEAD:RR",                                 "Frequenza respiratoria"),
            new Pair("LEAD:ETCO2",                              "Fine capnografia di marea"),
            new Pair("LEAD:ECG_I",                              "Elettrocardiografo Visualizza I"),
            new Pair("LEAD:ECG_II",                             "Elettrocardiografo Visualizza  II"),
            new Pair("LEAD:ECG_III",                            "Elettrocardiografo Visualizza  III"),
            new Pair("LEAD:ECG_AVR",                            "Elettrocardiografo Visualizza aVR"),
            new Pair("LEAD:ECG_AVL",                            "Elettrocardiografo Visualizza aVL"),
            new Pair("LEAD:ECG_AVF",                            "Elettrocardiografo Visualizza aVF"),
            new Pair("LEAD:ECG_V1",                             "Elettrocardiografo Visualizza V1"),
            new Pair("LEAD:ECG_V2",                             "Elettrocardiografo Visualizza V2"),
            new Pair("LEAD:ECG_V3",                             "Elettrocardiografo Visualizza V3"),
            new Pair("LEAD:ECG_V4",                             "Elettrocardiografo Visualizza V4"),
            new Pair("LEAD:ECG_V5",                             "Elettrocardiografo Visualizza V5"),
            new Pair("LEAD:ECG_V6",                             "Elettrocardiografo Visualizza V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "Visualizza I"),
            new Pair("LEAD:ECG_II__SHORT",                      "Visualizza  II"),
            new Pair("LEAD:ECG_III__SHORT",                     "Visualizza  III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "Visualizza aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "Visualizza aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "Visualizza aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "Visualizza V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "Visualizza V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "Visualizza V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "Visualizza V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "Visualizza V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "Visualizza V6"),
            new Pair("ABOUT:AboutProgram",                      "Informazioni sull'infermeria integrata"),
            new Pair("ABOUT:Version",                           "Versione {0}"),
            new Pair("ABOUT:Description",                       "Infermary Integrated è un software gratuito e open source sviluppato per promuovere la formazione sanitaria per medici e infermieri e studenti. Sviluppato come strumenti educativi approfonditi, accurati e accessibili, l'infermeria integrata è in grado di soddisfare le esigenze dei simulatori clinici in emergenza, terapia intensiva e molte altre specialità mediche e infermieristiche."),
            new Pair("LANG:LanguageSelection",                  "Selezione della lingua"),
            new Pair("LANG:ChooseLanguage",                     "Per favore scegli la tua lingua:"),
        };

        static List<Pair> PTB = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Continuar"),
            new Pair("BUTTON:ApplyChanges",                     "Aplicar mudanças"),
            new Pair("BUTTON:ResetParameters",                  "Parâmetros de redefinição"),
            new Pair("II:InfirmaryIntegrated",                  "Infirmary Integrated"),
            new Pair("RHYTHM:Asystole",                         "Asistolia"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Fibrilação atrial"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Flutter atrial"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "Bloco AV, 1º Grau"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "Bloco AV, 3º Grau"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "Bloco AV, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "Bloco AV, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Bundle Branch Block"),
            new Pair("RHYTHM:Idioventricular",                  "Idioventricular"),
            new Pair("RHYTHM:Junctional",                       "Juncional"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Atividade elétrica sem pulsos"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Ritmo sinusal"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Ritmo Sinusal com Bigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Ritmo Sinusal com Trigeminy"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Ritmo Sinusal com PACs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Ritmo Sinusal com PJCs"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Ritmo Sinusal com PVC (Multifocal)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Ritmo sinusal com PVC (Unifocal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Taquicardia supraventricular"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Fibrilação ventricular (grosseira)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Fibrilação ventricular (multa)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Stress Ventricular"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Taquicardia ventricular (monomórfica, pulsada)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Taquicardia Ventricular (Monomórfico, Sem Pulsos)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Taquicardia Ventricular (Polimórfica)"),
            new Pair("RHYTHM:Apnea",                            "Apnéia"),
            new Pair("RHYTHM:Regular",                          "Regular"),
            new Pair("PE:WindowTitle",                          "Infirmary Integrated: Editor de Pacientes"),
            new Pair("PE:MenuFile",                             "Arquivo"),
            new Pair("PE:MenuLoadSimulation",                   "Simulação de carga"),
            new Pair("PE:MenuSaveSimulation",                   "Save Simulation"),
            new Pair("PE:MenuExitProgram",                      "Exit Infirmary Integrated"),
            new Pair("PE:MenuSettings",                         "Configurações"),
            new Pair("PE:MenuSetLanguage",                      "Definir idioma"),
            new Pair("PE:MenuHelp",                             "Socorro"),
            new Pair("PE:MenuAboutProgram",                     "Sobre Infirmary Integrated"),
            new Pair("PE:Devices",                              "Dispositivos"),
            new Pair("PE:CardiacMonitor",                       "Monitor cardíaco"),
            new Pair("PE:12LeadECG",                            "12 ECG de chumbo"),
            new Pair("PE:Defibrillator",                        "Desfibrilador"),
            new Pair("PE:Ventilator",                           "Ventilador"),
            new Pair("PE:IABP",                                 "Bomba de balão intra-aórtico"),
            new Pair("PE:Cardiotocograph",                      "Cardiotocografia"),
            new Pair("PE:IVPump",                               "Bomba IV"),
            new Pair("PE:LabResults",                           "Resultados laboratoriais"),
            new Pair("PE:HeartRate",                            "Frequência cardíaca"),
            new Pair("PE:BloodPressure",                        "Pressão sanguínea"),
            new Pair("PE:RespiratoryRate",                      "Frequência respiratória"),
            new Pair("PE:PulseOximetry",                        "Oximetria de pulso"),
            new Pair("PE:Temperature",                          "Temperatura"),
            new Pair("PE:EndTidalCO2",                          "End Tidal CO2"),
            new Pair("PE:ArterialBloodPressure",                "Pressão Arterial"),
            new Pair("PE:CentralVenousPressure",                "Pressão Venosa Central"),
            new Pair("PE:PulmonaryArteryPressure",              "Pressão da artéria pulmonar"),
            new Pair("PE:RespiratoryRhythm",                    "Ritmo respiratório"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Razão Inspiratório-Expiratório"),
            new Pair("PE:CardiacRhythm",                        "Ritmo Cardíaco"),
            new Pair("PE:VitalSigns",                           "Sinais vitais"),
            new Pair("PE:AdvancedHemodynamics",                 "Hemodinâmica Avançada"),
            new Pair("PE:RespiratoryProfile",                   "Perfil Respiratório"),
            new Pair("PE:CardiacProfile",                       "Perfil cardíaco"),
            new Pair("PE:UseDefaultVitalSignRanges",            "Use padrões de registro vital padrão para seleções de ritmo?"),
            new Pair("PE:STSegmentElevation",                   "Elevação do segmento ST"),
            new Pair("PE:TWaveElevation",                       "Elevação da Onda T"),
            new Pair("CM:WindowTitle",                          "Infirmary Integrated: Monitor cardíaco"),
            new Pair("CM:MenuDeviceOptions",                    "Opções do dispositivo"),
            new Pair("CM:MenuPauseDevice",                      "Pause Device"),
            new Pair("CM:MenuAddTracing",                       "Adicionar formas de onda"),
            new Pair("CM:MenuAddNumeric",                       "Adicionar número"),
            new Pair("CM:MenuFontSize",                         "Tamanho da fonte"),
            new Pair("CM:MenuFontSizeDecrease",                 "Diminuir o tamanho da fonte"),
            new Pair("CM:MenuFontSizeIncrease",                 "Aumentar o tamanho da fonte"),
            new Pair("CM:MenuColorScheme",                      "Esquema de cores"),
            new Pair("CM:MenuToggleFullscreen",                 "Alternar para o modo tela cheia"),
            new Pair("CM:MenuCloseDevice",                      "Fechar dispositivo"),
            new Pair("CM:MenuExitProgram",                      "Saída Infirmary Integrated"),
            new Pair("CM:MenuRemoveTracing",                    "Remover a forma de onda"),
            new Pair("CM:MenuRemoveNumeric",                    "Remova números"),
            new Pair("CM:MenuSelectInputSource",                "Selecione a fonte de entrada"),
            new Pair("ECG:WindowTitle",                         "Infirmary Integrated: Eletrocardiograma"),
            new Pair("ECG:MenuDeviceOptions",                   "Opções do dispositivo"),
            new Pair("ECG:MenuPauseDevice",                     "Pause Device"),
            new Pair("ECG:MenuToggleFullscreen",                "Alternar para o modo tela cheia"),
            new Pair("ECG:MenuCloseDevice",                     "Fechar dispositivo"),
            new Pair("ECG:MenuExitProgram",                     "Exit Infirmary Integrated"),
            new Pair("NUMERIC:ECG",                             "Eletrocardiograma"),
            new Pair("NUMERIC:T",                               "Temperatura"),
            new Pair("NUMERIC:RR",                              "Frequência respiratória"),
            new Pair("NUMERIC:ETCO2",                           "Captografia final da maré"),
            new Pair("NUMERIC:SPO2",                            "Oximetria de pulso"),
            new Pair("NUMERIC:NIBP",                            "Pressão sanguínea não-invasiva"),
            new Pair("NUMERIC:ABP",                             "Pressão Arterial"),
            new Pair("NUMERIC:CVP",                             "Pressão Venosa Central"),
            new Pair("NUMERIC:PA",                              "Pressão da artéria pulmonar"),
            new Pair("TRACING:ECG",                             "Eletrocardiograma"),
            new Pair("LEAD:SPO2",                               "Oximetria de pulso"),
            new Pair("LEAD:CVP",                                "Pressão Venosa Central"),
            new Pair("LEAD:ABP",                                "Pressão Arterial"),
            new Pair("LEAD:PA",                                 "Pressão da artéria pulmonar"),
            new Pair("LEAD:RR",                                 "Frequência respiratória"),
            new Pair("LEAD:ETCO2",                              "Captografia final da maré"),
            new Pair("LEAD:ECG_I",                              "Electrocardiógrafo Ver I"),
            new Pair("LEAD:ECG_II",                             "Electrocardiógrafo Ver II"),
            new Pair("LEAD:ECG_III",                            "Electrocardiógrafo Ver III"),
            new Pair("LEAD:ECG_AVR",                            "Electrocardiógrafo Ver aVR"),
            new Pair("LEAD:ECG_AVL",                            "Electrocardiógrafo Ver aVL"),
            new Pair("LEAD:ECG_AVF",                            "Electrocardiógrafo Ver aVF"),
            new Pair("LEAD:ECG_V1",                             "Electrocardiógrafo Ver V1"),
            new Pair("LEAD:ECG_V2",                             "Electrocardiógrafo Ver V2"),
            new Pair("LEAD:ECG_V3",                             "Electrocardiógrafo Ver V3"),
            new Pair("LEAD:ECG_V4",                             "Electrocardiógrafo Ver V4"),
            new Pair("LEAD:ECG_V5",                             "Electrocardiógrafo Ver V5"),
            new Pair("LEAD:ECG_V6",                             "Electrocardiógrafo Ver V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "Ver I"),
            new Pair("LEAD:ECG_II__SHORT",                      "Ver II"),
            new Pair("LEAD:ECG_III__SHORT",                     "Ver III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "Ver aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "Ver aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "Ver aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "Ver V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "Ver V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "Ver V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "Ver V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "Ver V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "Ver V6"),
            new Pair("ABOUT:AboutProgram",                      "Sobre Infirmary Integrated"),
            new Pair("ABOUT:Version",                           "Versão {0}"),
            new Pair("ABOUT:Description",                       "Infirmary Integrated é um software livre e de código aberto desenvolvido para promover a educação em saúde para profissionais e estudantes de medicina e enfermagem. Desenvolvido como ferramentas educacionais detalhadas, precisas e acessíveis, a Infirmary Integrated pode atender às necessidades de simuladores clínicos em atendimento urgente, crítico e muitas outras especialidades médicas e de enfermagem."),
            new Pair("LANG:LanguageSelection",                  "Seleção de idioma"),
            new Pair("LANG:ChooseLanguage",                     "Escolha o seu idioma:"),
        };

        static List<Pair> RUS = new List<Pair> {
            new Pair("BUTTON:Continue",                         "Продолжать"),
            new Pair("BUTTON:ApplyChanges",                     "Применить изменения"),
            new Pair("BUTTON:ResetParameters",                  "Сбросить параметры"),
            new Pair("II:InfirmaryIntegrated",                  "Интегрированный комплекс"),
            new Pair("RHYTHM:Asystole",                         "асистолия"),
            new Pair("RHYTHM:Atrial_Fibrillation",              "Фибрилляция предсердий"),
            new Pair("RHYTHM:Atrial_Flutter",                   "Предсердный флаттер"),
            new Pair("RHYTHM:AV_Block__1st_Degree",             "AV-блок, 1-я степень"),
            new Pair("RHYTHM:AV_Block__3rd_Degree",             "Блок AV, 3-я степень"),
            new Pair("RHYTHM:AV_Block__Mobitz_II",              "AV Block, Mobitz II"),
            new Pair("RHYTHM:AV_Block__Wenckebach",             "AV Block, Wenckebach"),
            new Pair("RHYTHM:Bundle_Branch_Block",              "Межжелудочковая блокада"),
            new Pair("RHYTHM:Idioventricular",                  "идиовентрикулярный"),
            new Pair("RHYTHM:Junctional",                       "Junctional"),
            new Pair("RHYTHM:Pulseless_Electrical_Activity",    "Электрическая активность"),
            new Pair("RHYTHM:Sinus_Rhythm",                     "Синусовый ритм"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Bigeminy",       "Синус Ритм с Бигеминой"),
            new Pair("RHYTHM:Sinus_Rhythm_with_Trigeminy",      "Синусовый ритм с тригеминой"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PACs",           "Синусовый ритм с PAC"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PJCs",           "Синусовый ритм с PJC"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Multifocal","Синусовый ритм с ПВХ (мультифокальный)"),
            new Pair("RHYTHM:Sinus_Rhythm_with_PVCs_Unifocal",  "Синус Rhythm с ПВХ (Unifocal)"),
            new Pair("RHYTHM:Supraventricular_Tachycardia",     "Суправентрикулярная тахикардия"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Coarse",  "Фибрилляция желудочков (грубая)"),
            new Pair("RHYTHM:Ventricular_Fibrillation_Fine",    "Фибрилляция желудочков (тонкая)"),
            new Pair("RHYTHM:Ventricular_Standstill",           "Концентрация желудочков"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulsed","Желудочковая тахикардия (мономорфная, импульсная)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Monomorphic_Pulseless","Желудочковая тахикардия (мономорфная, безболезненная)"),
            new Pair("RHYTHM:Ventricular_Tachycardia_Polymorphic","Желудочковая тахикардия (полиморфная)"),
            new Pair("RHYTHM:Apnea",                            "Апноэ"),
            new Pair("RHYTHM:Regular",                          "регулярное"),
            new Pair("PE:WindowTitle",                          "Интегрированный комплекс: Редактор пациента"),
            new Pair("PE:MenuFile",                             "файл"),
            new Pair("PE:MenuLoadSimulation",                   "Моделирование нагрузки"),
            new Pair("PE:MenuSaveSimulation",                   "Сохранить моделирование"),
            new Pair("PE:MenuExitProgram",                      "Выход из интернатуры Интегрированный"),
            new Pair("PE:MenuSettings",                         "настройки"),
            new Pair("PE:MenuSetLanguage",                      "Установить язык"),
            new Pair("PE:MenuHelp",                             "Помогите"),
            new Pair("PE:MenuAboutProgram",                     "О комплексе"),
            new Pair("PE:Devices",                              "приборы"),
            new Pair("PE:CardiacMonitor",                       "Сердечный монитор"),
            new Pair("PE:12LeadECG",                            "12 ЭКГ ЭКГ"),
            new Pair("PE:Defibrillator",                        "дефибриллятор"),
            new Pair("PE:Ventilator",                           "вентилятор"),
            new Pair("PE:IABP",                                 "Внутриаортальный воздушный насос"),
            new Pair("PE:Cardiotocograph",                      "Кардиотокография"),
            new Pair("PE:IVPump",                               "IV насос"),
            new Pair("PE:LabResults",                           "Лабораторные результаты"),
            new Pair("PE:HeartRate",                            "Частота сердцебиения"),
            new Pair("PE:BloodPressure",                        "Кровяное давление"),
            new Pair("PE:RespiratoryRate",                      "Частота дыхания"),
            new Pair("PE:PulseOximetry",                        "Пульсовая оксиметрия"),
            new Pair("PE:Temperature",                          "температура"),
            new Pair("PE:EndTidalCO2",                          "Конец приливной капнографии"),
            new Pair("PE:ArterialBloodPressure",                "Артериальное кровяное давление"),
            new Pair("PE:CentralVenousPressure",                "Центральное венозное давление"),
            new Pair("PE:PulmonaryArteryPressure",              "Давление легочной артерии"),
            new Pair("PE:RespiratoryRhythm",                    "Дыхательный ритм"),
            new Pair("PE:InspiratoryExpiratoryRatio",           "Вдохново-экспираторный коэффициент"),
            new Pair("PE:CardiacRhythm",                        "Сердечный ритм"),
            new Pair("PE:VitalSigns",                           "Жизненно важные признаки"),
            new Pair("PE:AdvancedHemodynamics",                 "Продвинутая гемодинамика"),
            new Pair("PE:RespiratoryProfile",                   "Респираторный профиль"),
            new Pair("PE:CardiacProfile",                       "Профиль сердца"),
            new Pair("PE:UseDefaultVitalSignRanges",            "Использовать диапазоны жизненно важных значений по умолчанию для выбора ритма?"),
            new Pair("PE:STSegmentElevation",                   "Высота сегмента ST"),
            new Pair("PE:TWaveElevation",                       "Высота волны T"),
            new Pair("CM:WindowTitle",                          "Инвалидный комплекс: Сердечный монитор"),
            new Pair("CM:MenuDeviceOptions",                    "Параметры устройства"),
            new Pair("CM:MenuPauseDevice",                      "Приостановить устройство"),
            new Pair("CM:MenuAddTracing",                       "Добавить осциллограммы"),
            new Pair("CM:MenuAddNumeric",                       "добавить номер"),
            new Pair("CM:MenuFontSize",                         "Размер шрифта"),
            new Pair("CM:MenuFontSizeDecrease",                 "Уменьшить размер шрифта"),
            new Pair("CM:MenuFontSizeIncrease",                 "Увеличить размер шрифта"),
            new Pair("CM:MenuColorScheme",                      "Цветовая схема"),
            new Pair("CM:MenuToggleFullscreen",                 "Включить полноэкранный режим"),
            new Pair("CM:MenuCloseDevice",                      "Закрыть устройство"),
            new Pair("CM:MenuExitProgram",                      "Выход из интернатуры Интегрированный"),
            new Pair("CM:MenuRemoveTracing",                    "Удалить форму волны"),
            new Pair("CM:MenuRemoveNumeric",                    "Удалить номера"),
            new Pair("CM:MenuSelectInputSource",                "Выбор источника входного сигнала"),
            new Pair("ECG:WindowTitle",                         "Инвалидный комплекс: Электрокардиограф"),
            new Pair("ECG:MenuDeviceOptions",                   "Параметры устройства"),
            new Pair("ECG:MenuPauseDevice",                     "Приостановить устройство"),
            new Pair("ECG:MenuToggleFullscreen",                "Включить полноэкранный режим"),
            new Pair("ECG:MenuCloseDevice",                     "Закрыть устройство"),
            new Pair("ECG:MenuExitProgram",                     "Выход из интернатуры Интегрированный"),
            new Pair("NUMERIC:ECG",                             "Электрокардиограф"),
            new Pair("NUMERIC:T",                               "температура"),
            new Pair("NUMERIC:RR",                              "Частота дыхания"),
            new Pair("NUMERIC:ETCO2",                           "Конец приливной капнографии"),
            new Pair("NUMERIC:SPO2",                            "Пульсовая оксиметрия"),
            new Pair("NUMERIC:NIBP",                            "Неинвазивное кровяное давление"),
            new Pair("NUMERIC:ABP",                             "Артериальное кровяное давление"),
            new Pair("NUMERIC:CVP",                             "Центральное венозное давление"),
            new Pair("NUMERIC:PA",                              "Давление легочной артерии"),
            new Pair("TRACING:ECG",                             "Электрокардиограф"),
            new Pair("LEAD:SPO2",                               "Пульсовая оксиметрия"),
            new Pair("LEAD:CVP",                                "Центральное венозное давление"),
            new Pair("LEAD:ABP",                                "Артериальное кровяное давление"),
            new Pair("LEAD:PA",                                 "Давление легочной артерии"),
            new Pair("LEAD:RR",                                 "Частота дыхания"),
            new Pair("LEAD:ETCO2",                              "Конец приливной капнографии"),
            new Pair("LEAD:ECG_I",                              "Электрокардиограф Посмотреть I"),
            new Pair("LEAD:ECG_II",                             "Электрокардиограф Посмотреть II"),
            new Pair("LEAD:ECG_III",                            "Электрокардиограф Посмотреть III"),
            new Pair("LEAD:ECG_AVR",                            "Электрокардиограф Посмотреть aVR"),
            new Pair("LEAD:ECG_AVL",                            "Электрокардиограф Посмотреть aVL"),
            new Pair("LEAD:ECG_AVF",                            "Электрокардиограф Посмотреть aVF"),
            new Pair("LEAD:ECG_V1",                             "Электрокардиограф Посмотреть V1"),
            new Pair("LEAD:ECG_V2",                             "Электрокардиограф Посмотреть V2"),
            new Pair("LEAD:ECG_V3",                             "Электрокардиограф Посмотреть V3"),
            new Pair("LEAD:ECG_V4",                             "Электрокардиограф Посмотреть V4"),
            new Pair("LEAD:ECG_V5",                             "Электрокардиограф Посмотреть V5"),
            new Pair("LEAD:ECG_V6",                             "Электрокардиограф Посмотреть V6"),
            new Pair("LEAD:ECG_I__SHORT",                       "I"),
            new Pair("LEAD:ECG_II__SHORT",                      "II"),
            new Pair("LEAD:ECG_III__SHORT",                     "III"),
            new Pair("LEAD:ECG_AVR__SHORT",                     "aVR"),
            new Pair("LEAD:ECG_AVL__SHORT",                     "aVL"),
            new Pair("LEAD:ECG_AVF__SHORT",                     "aVF"),
            new Pair("LEAD:ECG_V1__SHORT",                      "V1"),
            new Pair("LEAD:ECG_V2__SHORT",                      "V2"),
            new Pair("LEAD:ECG_V3__SHORT",                      "V3"),
            new Pair("LEAD:ECG_V4__SHORT",                      "V4"),
            new Pair("LEAD:ECG_V5__SHORT",                      "V5"),
            new Pair("LEAD:ECG_V6__SHORT",                      "V6"),
            new Pair("ABOUT:AboutProgram",                      "О комплексе"),
            new Pair("ABOUT:Version",                           "Версия {0}"),
            new Pair("ABOUT:Description",                       "Infirmary Integrated - бесплатное программное обеспечение с открытым исходным кодом, разработанное для продвижения медицинского образования для медицинских и сестринских специалистов и студентов. Разработанный как углубленный, точный и доступный образовательный инструмент, Infirmary Integrated может удовлетворить потребности клинических тренажеров в неотложной, критической медицинской помощи и многих других медицинских и сестринских специальностях."),
            new Pair("LANG:LanguageSelection",                  "Выбор языка"),
            new Pair("LANG:ChooseLanguage",                     "Выберите язык:"),
        };
    }
}
